# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

jobs: 
  - job: install
    pool:
      vmImage: ubuntu-latest
    steps:

        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - script: npm install
          displayName: 'NPM Install'

          # need to cache

  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:

        - script: npm run build 
          displayName: 'npm install and build'

        - task: CopyFiles@2
          inputs:
            SourceFolder: './build'
            TargetFolder: $(Build.ArtifactStagingDirectory)

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

  - job: test
    pool:
      vmImage: ubuntu-latest
    steps:

        - script: npm test
          displayName: 'Run Unit Tests'